import os
os.system ('clear')
os.system ('clear')                                                                                  
os.system ('sl')
os.system('clear')
print ('\033[1;36mحﺎﭴﻧﺑ مﺗ')
os.system ('figlet free fire  |lolcat')
print ("")
print ("")
print (" \033[1;32m بﺎﺴﺤﻟ عوﻧ  \033[1;33m: Gmail")
print ("")
print ("")
print (" \033[1;32mفﺗﺎﮩﻟ مﻗر/ ﺪﯾﺮﺑ \033[1;33m: mhamdmohamd004@gmail.com")
print ("")
print ("")
print (" \033[1;32mةﺮﻏﺗ :\033[1;33m mohamd2002")
print ("")
print ("")
os.system ('figlet')

